### ISSUE TITLE
Unifying Service fn/access to support functions with Generic parameters

### ISSUE THREAD

**Issue by patroza** [Matechs-Garage/matechs-effect#272]
I think there should be one canonical way to define and consume services.
Since the Service access implementation currently does not support Generics, this means there are multiple ways.

I hope we can identify and document the problem / limitation and somehow look towards resolving it.
So far, using `Service.define`, `.fn`, `.TypeOf` etc seems to be fine with Generic functions, but `.access` specifically blocks it.

Im personally using a workaround to support it, with so far no issues/downsides, other than the inconvenience of using it separately or patching Service :)

**Comment by mikearnaldi** [comment]
@patroza there is simply no way to do this. The reason is access & implement, etc. make use of infer and infer erase generics to unknown. This is the reason why it is explicitly blocked.

The canonical way of using generics is to avoid usage of `Service` and use the classical way with definition of an interface and definition of the access helpers manually.

You can post your workaround and we can evaluate if it is a viable alternative

**Comment by mikearnaldi** [comment]
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=16&pc=14#code/GYVwdgxgLglg9mABAdxlAFgcQKZmwJxggB4AVAPgAoBDALkVIEp7TEBvAKEW8X2yhD4k1DgF8OHCAgDOURAHlEAXnZceqDDjyEIYiVACeAB2yIAkmGAFiAaXLLVPRAG0A1ohhJX2A3GCIbAF16GzdAxGwADyhcABNpREoAfXpPK3xEAEFGZXs0gkQAIUQAfkSUrJyle2L6PAA3Aj0OWOwIABtqPkQpMFke+gt04kMTPwVyCQB6KfL6cFcwOGQwKvsFpZXJADoNLFwCIiA

**Comment by mikearnaldi** [comment]
This is getting removed in favour of the new Has mechanism in the next major #277

**Comment by mikearnaldi** [comment]
Confirm removal in next major release, reason being both Has is better and TS 4 has restricted usage of recursive types to shape interfaces (Service no longer works)
