### ISSUE TITLE
why provideAll and other provides functions are removed?

### ISSUE THREAD

**Issue by mohaalak** [Matechs-Garage/matechs-effect#294]
in version 5.0.2 that I was working with, there were some functions to provide  environments that makes it so easy but right now there is only `provide`, `provideM`.

let me explain it in an example

```
interface Env1 {
  k: number;
  b: number;
}

interface Env2 {
  k: number;
  c: number;
}
pipe(
  EFF.pure(10),
  EFF.chain((y) => EFF.access(({ k }: Env1) => y + k)),
  EFF.chain((y) => EFF.access(({ c }: Env2) => y + c)),
  EFF.provide({ k: 10, b: 10, c: 10 }),
  EFF.runToPromise
).then(console.log);

```

right now this code will have error and I don't even I can fix it, but in version 5 there was a `provideAll` that was simple and easy to use.

think about k,c,b as database repositories that I wan to use and each function have mix and match of these repositories. in the last versions I can easily `provideAll` repositories in production but in tests I can test out every function that I want and I know exactly what repositories they need.
but now I should provide each repository one by one that is tedious I don't know why it has been removed.

**Comment by mikearnaldi** [comment]
`provideAll` was removed in favour of `provideR` but I realise for inference is actually better to have also `provideAll` so that is re-added:
https://github.com/Matechs-Garage/matechs-effect/commit/465ab4f6d7e0b1783f967d2fc895643ac8061431

The remaining provider functions have been compacted in the current "provide" variants that also accept a second parameter, the only actual removal was for the provideStruct functions because they had problems at the type level.

One note that I might add, the preferred way to construct environments is via "Layer" that basically creates a managed environment, that can be very helpful if you embed in environment things like database connections

**Comment by mohaalak** [comment]
wow thanks for fast response.
I should read zio documentation for layers so I get what is going on.
